import { Program, AnchorProvider, BN } from '@coral-xyz/anchor';
import { PublicKey, Connection, Keypair } from '@solana/web3.js';
import { OnchainAcademy } from './types/onchain_academy'; // Generated by Anchor
import IDL from './academy.json';
import { PROGRAM_ID } from './constants';

/**
 * Initialize Anchor program instance
 * For browser/frontend use with wallet adapter provider
 */
export function getProgram(provider: AnchorProvider): Program<OnchainAcademy> {
  return new Program<OnchainAcademy>(
    IDL as any,
    PROGRAM_ID,
    provider
  );
}

/**
 * Initialize Anchor program with custom connection and keypair
 * For backend use with server signer
 */
export function getProgramWithKeypair(
  connection: Connection,
  payer: Keypair
): Program<OnchainAcademy> {
  const provider = new AnchorProvider(connection, { publicKey: payer.publicKey, signAllTransactions: async (txs) => txs, signTransaction: async (tx) => tx } as any, { commitment: 'confirmed' });
  
  return new Program<OnchainAcademy>(
    IDL as any,
    PROGRAM_ID,
    provider
  );
}

/**
 * Convert BN to number safely (for display)
 */
export function bnToNumber(value: BN): number {
  return value.toNumber();
}

/**
 * Convert number to BN
 */
export function numberToBn(value: number): BN {
  return new BN(value);
}

/**
 * Create BN with large value (for I80F48 fixed-point)
 */
export function createI80F48(value: number | bigint): { value: BN } {
  return {
    value: new BN(value),
  };
}
